### ISSUE TITLE
Doesent seem to work

### ISSUE THREAD

**Issue by valzzu** [MineTech13/homeassistant-basestation#1]
i set this up as was shown but the switches don't show up, only the group does.

**Comment by valzzu** [comment]
nvm, idk what i did but now it works.

**Comment by systemofapwne** [comment]
What was your solution?
I am in the same situation. My basestations can bee seen by my ESP32 bluetooth proxies:

![Image](https://github.com/user-attachments/assets/acab1bf2-fe75-48cd-9dc4-a1b3ca455f0d)

The integration has been added via HACS and I configured my basestations according to the readme.

/config/include/switch
```yaml
- name: "wohnzimmer_schrank_lhb"
  platform: basestation
  mac: "EA:3C:98:79:E5:7F"

- name: "wohnzimmer_fenster_lhb"
  platform: basestation
  mac: "FC:4B:67:DF:AD:62"
```

and `configuration.yaml` is including it
```yaml
#... other code
switch: !include_dir_merge_named include/switch/
#... other code
```

It makes no difference, if I directly configure it via the `configuration.yaml` or include it via `!include_dir_merge_named`. The basestations simply wont show up.

**Comment by MineTech13** [comment]
Heya, sorry for not replying this issue just somehow completely went past me is the issue still up or not?

**Comment by systemofapwne** [comment]
Well, it now seems to somewhat work, after I disabled my phones bluetooth. On my phone, I use [this app](https://github.com/jeroen1602/lighthouse_pm/releases) to control the base stations.
When I restart HA with my phones BT on, the basestations are not found.
However when I disable my phones BT and restart HA, the basestations are found.

This somewhat soundssimilar to https://github.com/jariz/homeassistant-basestation/issues/10

**Comment by MineTech13** [comment]
It is understandable that this issue appears to be similar to the one reported on Jariz, as this repository is essentially a fork with two fixes and has been updated for inclusion in HACS.

I will attempt to replicate the issue myself. It is possible that this may be related to another occasional issue I experience. At times, Home Assistant indicates that there is no connection to the base station when I attempt to control it. When this occurs, it also fails to connect to my index. However, after power cycling the base station, it reconnects successfully. It is possible that my phone or some other interference may also contribute to this problem.

I will reopen this issue for now until I gather more information. I hope this situation is rectifiable and not simply a case of devices conflicting over control.

**Comment by MineTech13** [comment]
I've pushed a new little experimental update that optimized a few things as well could you check if those optimisations fixed the issue because i must say i wasnt realy able to reproduce the issue only when my phone is actively scanning with lighthouse PM the basestations go unresponsive in home assistant for me but when i close the app on the phone the catch themselves after a few seconds (also honestly i didnt test with the old version only with the new experimental on cuz its much more clean)

@systemofapwne @valzzu

**Comment by systemofapwne** [comment]
> I've pushed a new little experimental update that optimized a few things as well could you check if those optimisations fixed the issue because i must say i wasnt realy able to reproduce the issue only when my phone is actively scanning with lighthouse PM the basestations go unresponsive in home assistant for me but when i close the app on the phone the catch themselves after a few seconds (also honestly i didnt test with the old version only with the new experimental on cuz its much more clean)
> 
> [@systemofapwne](https://github.com/systemofapwne) [@valzzu](https://github.com/valzzu)

I guess the update you are referring to, is the 2.0.0-alpha000?

**Comment by MineTech13** [comment]
> > I've pushed a new little experimental update that optimized a few things as well could you check if those optimisations fixed the issue because i must say i wasnt realy able to reproduce the issue only when my phone is actively scanning with lighthouse PM the basestations go unresponsive in home assistant for me but when i close the app on the phone the catch themselves after a few seconds (also honestly i didnt test with the old version only with the new experimental on cuz its much more clean)
> > [@systemofapwne](https://github.com/systemofapwne) [@valzzu](https://github.com/valzzu)
> 
> I guess the update you are referring to, is the 2.0.0-alpha000?

jup

**Comment by systemofapwne** [comment]
Sorry for the late reply.

The updated integration works for me and the config-flow option makes it so much more user friendly.

My discovered problems however still exist: Whenever another BT application seem to have a lock on the LHBs, this integration here wont be able to interact with the LHBs.

```python
2025-04-09 19:53:11.522 DEBUG (MainThread) [custom_components.basestation.switch] Failed to execute write
 on basestation 'EA:3C:98:79:E5:7F': Timeout waiting for connect response while connecting to EA:3C:98:79
:E5:7F after 10s, disconnect timed out: False,  after 20.0s 
2025-04-09 19:53:21.761 DEBUG (MainThread) [custom_components.basestation.switch] Failed to execute write
 on basestation 'FD:4B:67:DF:AD:62': Timeout waiting for connect response while connecting to FD:4B:67:DF
:AD:62 after 10s, disconnect timed out: False,  after 20.0s 
```

By simply turning off the "Lighthouse PM" app on my phone, the integration however sucessfully took over.

**Comment by MineTech13** [comment]
> Sorry for the late reply.
> 
> The updated integration works for me and the config-flow option makes it so much more user friendly.
> 
> My discovered problems however still exist: Whenever another BT application (e.g. the "Lighthouse PM" app on my phone) seem to have a lock on the LHBs, this integration here wont be able to interact with the LHBs.
> 
> 2025-04-09 19:53:11.522 DEBUG (MainThread) [custom_components.basestation.switch] Failed to execute write
>  on basestation 'EA:3C:98:79:E5:7F': Timeout waiting for connect response while connecting to EA:3C:98:79
> :E5:7F after 10s, disconnect timed out: False,  after 20.0s 
> 2025-04-09 19:53:21.761 DEBUG (MainThread) [custom_components.basestation.switch] Failed to execute write
>  on basestation 'FD:4B:67:DF:AD:62': Timeout waiting for connect response while connecting to FD:4B:67:DF
> :AD:62 after 10s, disconnect timed out: False,  after 20.0s 
> But by simply turning off the "Lighthouse PM" app on my phone, the integration however sucessfully took over and finished the task I have asked it before. Seems like you added a command-queue that is repeated, until a task was successful. This sounds like a great addition.

well i cant override the lock that another app has over a device thats a cold hard fact but with some optimizations and help i made the whole system more robust im also gonna improve a little more and then draft a release ^^ but good to get some validation that this update is working as expected ^^ ima close this issue then as its working as good as it can be
